### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by tykm** [A-Minus-Team/weather-wear#15]
User can view their current profile picture and upload a new one.
User can adjust their name.

**Comment by ezhang123** [comment]
Updating profile picture, adjusting names, etc were deemed out of the scope for the project. We realized our app wasn't a social media app, the user would not be able to connect with others and the features were redundant. We have replace this feature with a different one and merged them with "app setting". The new feature is the ability to upload and change your zipcode in order to change the weather. That current feature is not fully done, it is currently only able to upload zipcodes, not update. Will continue in milestone 4, our team is ahead of schedule and "edit profile" feature was optional to begin with.
